# Generated by Django 5.0.4 on 2024-04-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0004_alter_faculty_options_alter_teacher_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='faculty',
            new_name='kafedra',
        ),
    ]
