# Generated by Django 5.0.4 on 2024-04-26 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('answers', models.ManyToManyField(to='question_app.answer')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.teacher')),
            ],
            options={
                'verbose_name': 'Talaba Javobi',
                'verbose_name_plural': 'Talaba Javoblari',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.question')),
            ],
            options={
                'verbose_name': 'Talaba Ovozi',
                'verbose_name_plural': 'Talaba Ovozlari',
            },
        ),
    ]
